---

server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/TheGaneshkumawat/mc-config # default
          username: abc
          password: abc
          search-paths:
            - 'station*'
                #uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-local # alt
                #search-paths:
                # - 'station*'
  security:
    basic:
      enabled: false
    user:
      name: ganesh
      password: ganesh
